### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by johnwalker00** [mhan810/aws-elb-load-shedding#1]
PS C:\repos\aws-elb-load-shedding\cdk> cdk synth
Traceback (most recent call last):
  File "C:\repos\aws-elb-load-shedding\cdk\app.py", line 18, in <module>
    ALBCloudWatchStack(app, 'ALBCloudWatchStack',
  File "C:\Users\johnwalb\AppData\Roaming\Python\Python39\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\repos\aws-elb-load-shedding\cdk\cdk\alb_monitor_stack.py", line 137, in __init__
    target_group_dimension = elb_target_group_arn[elb_target_group_arn.find(
AttributeError: 'NoneType' object has no attribute 'find'
Subprocess exited with error 1

**Comment by mhan810** [comment]
This is because you didn't provide a -c elbTargetGroupArn as part of the cdk command. I added information in the readme file. Will throw an error if this parameter isn't specified.

**Comment by mhan810** [comment]
see https://github.com/mhan810/aws-elb-load-shedding/commit/728701b00bdfb62b5be8c8e0208c1565f306406a
